import "./globals.css"
import NextAuthProvider from "@/src/providers/NextAuthProvider";
import Layout from "@/src/components/layout/Layout";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <NextAuthProvider>
            <Layout>
                {children}
            </Layout>
        </NextAuthProvider>
        </body>
        </html>
    );
}
